### ISSUE TITLE
Ansible all the dhcpd

### ISSUE THREAD

**Issue by RichiH** [FOSDEM/infrastructure#102]
https://github.com/FOSDEM/video/issues/58

**Comment by msuriar** [comment]
Having had a poke around in here, it appears that this is what we need:

http://debops-documentation-testing.readthedocs.io/en/latest/ansible/roles/ansible-dhcpd/docs/defaults-configuration.html#dhcpd-hosts

See 03321f8 for an example

Ideally I want all the static leases in a single external file, but it's not clear from the docs whether that should be YAML or raw dhcpd.conf syntax. Grr.

**Comment by msuriar** [comment]
I think this is now done.
