### ISSUE TITLE
make sure not to write smartmon.prom elsewhere than SD

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/infrastructure#113]
/srv/node_exporter/textfiles/smartmon.prom gets written every minute. In the case of the video boxes, to the SD card.

This should at the very least be made configurable, so we can avoid writing to the SD..

**Comment by SuperQ** [comment]
Yup, it should already be configurable, we can put that in a group_vars template.

**Comment by gerryd** [comment]
I've updated the group_vars for the video boxes. The node_exporter binaries and textfiles are now on the SSD. I've also added a skip for the untar task if the correct version of node_exporter was already present. This saves us quite some time when deploying videoboxes which don't have a lot of CPU power.
