### ISSUE TITLE
mtail fails on startup

### ISSUE THREAD

**Issue by gerryd** [FOSDEM/infrastructure#116]
On the stream frontends, backends and webserver (which hosts the browser video player), we install mtail to help gather statistics.

Starting the mtail service fails:

    F1228 13:42:21.297228   14758 main.go:68] couldn't start: Compile encountered errors:
    compile failed for nginx.mtail:
    nginx.mtail:30:5-28: Identifier `http_m3u8_requests_total' not declared.
    	Try adding `counter http_m3u8_requests_total' to the top of the program.
    nginx.mtail:33:5-26: Identifier `http_ts_requests_total' not declared.
	Try adding `counter http_ts_requests_total' to the top of the program.

Probably not relevant since the same issue existed before I did this, but for completeness' sake: I changed the mtail role to use a Debian package instead of the tarball.

**Comment by bastischubert** [comment]
we'll move over to promtail for the log based metrics generation (https://github.com/FOSDEM/video/issues/46) - will close this and continue in https://github.com/FOSDEM/video/issues/46
