### ISSUE TITLE
Use prometheus-node-exporter from packages

### ISSUE THREAD

**Issue by gerryd** [FOSDEM/infrastructure#117]
I noticed `prometheus-node-exporter` is now packaged for Debian. Stretch seems to have version 0.13.0, which is the one we're currently running.

Could you look into using that instead of the tarball?

**Comment by SuperQ** [comment]
I will be working on updating the ansible config for Prometheus components.  Not likely using Debian packages as they are very old.

**Comment by SuperQ** [comment]
Sadly, the Debian packages are too far behind for production use. I would prefer to keep using the Cloudalchemy ansible roles, as they're auto-updated when Prometheus official releases are cut. Debian just doesn't have the automation required for modern use.
