### ISSUE TITLE
Update ULB DNS entries

### ISSUE THREAD

**Issue by SuperQ** [FOSDEM/infrastructure#120]
`server001.sk1-510.k.ulb.bru.fosdem.net`:
* A `185.175.216.250`
* AAAA `2001:67c:1810:f054:baca:3aff:fef7:402c`
* CNAME `server001.fosdem.net.`

`server002.sk1-510.k.ulb.bru.fosdem.net`:
* A `185.175.216.252`
* AAAA `2001:67c:1810:f054:baca:3aff:fef7:4f75`
* CNAME `server002.fosdem.net.`

**Comment by SuperQ** [comment]
Since this is taking some time, I decided to re-IP server001 to the old IP, it's now `185.175.216.250`.  I will update the issue to match.

**Comment by corosuske** [comment]
this has been done
