### ISSUE TITLE
no dhcp on video vlan

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/infrastructure#155]
Hello,

As notified by email yesterdatn, and as per your request to file here, we will be running our own dhcp server on the video vlan, so please disable the central dhcp server there.

Kind regards,

Mark

**Comment by pvaneynd** [comment]
Removed the DHCP server on the router for 151.216.192.0/255.255.224.0

**Comment by SuperQ** [comment]
I still need to cleanup some DHCP server cruft on the event server.
