### ISSUE TITLE
Network configuration  - Static DHCP lease for the printer

### ISSUE THREAD

**Issue by gerryd** [FOSDEM/infrastructure#16]
Please configure a static DHCP lease for the on-site printer. Its MAC address will be 00:1b:a9:3b:b3:90.

**Comment by pvaneynd** [comment]
What IP should it get?

**Comment by RichiH** [comment]
We will redo the ip blocks after the weekend when we have nipap.

Richard

Sent by mobile; excuse my brevity.

**Comment by ghosty-be** [comment]
other printer MAC addresses:
00:80:77:ec:2e:7c
00:80:77:ec:2e:61
00:80:77:ec:2e:75
I will bring 2 out of these 3, not sure which though
