### ISSUE TITLE
Fix chrony deploy iteritems() issue

### ISSUE THREAD

**Issue by SuperQ** [FOSDEM/infrastructure#195]
We ran into an issue with iteritems() in the chrony deploy.

@yoe: Can you paste the error message you got?

**Comment by SuperQ** [comment]
@paulfantom suspects that this is a Python 2/3 issue and we need to replace `iteritems()` with `items()`.

**Comment by SuperQ** [comment]
My ansible:
```
ansible 2.7.6
  config file = /home/ben/src/FOSDEM/infrastructure/ansible/ansible.cfg
  configured module search path = [u'/home/ben/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

**Comment by SuperQ** [comment]
My ansible:
```
$ ansible --version
ansible 2.7.6
  config file = /home/ben/src/FOSDEM/infrastructure/ansible/ansible.cfg
  configured module search path = [u'/home/ben/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

**Comment by yoe** [comment]
wouter@gangtai:~$ ansible --version
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/wouter/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2+ (default, Feb  2 2019, 14:31:48) [GCC 8.2.0]

That could be the reason, indeed.

-- 
To the thief who stole my anti-depressants: I hope you're happy

  -- seen somewhere on the Internet on a photo of a billboard
