### ISSUE TITLE
checksum downloads cause 429 error

### ISSUE THREAD

**Issue by SuperQ** [FOSDEM/infrastructure#226]
cc @gerryd 

When deploying to the big list of video boxes, the github releases download of the `sha256sums.txt` happens in parallel from all the nodes in a very short time, triggering GitHub to 429 error the requests.

```
fatal: [ua2220-slides.video.fosdem.org]: FAILED! => {
  "msg": "An  unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Received HTTP error for https://github.com/FOSDEM/video-sproxy/releases/download/v0.2.2/sha256sums.txt : HTTPError 429: Too Many Requests"
}
```

We should only hit this once in setup, avoiding the need to execute it for every node.

https://github.com/FOSDEM/infrastructure/blob/master/ansible/playbooks/roles/sproxy/tasks/main.yml#L2-L8

cc @paulfantom, do you have any ideas?

**Comment by SuperQ** [comment]
Maybe it would work to set `delegate_to: localhost`

**Comment by krokodilerian** [comment]
The options in my head look like this (no order of preference):

1) get a CDN-like service in front of this that doesn't crap out this fast, something cloudflare-like.
2) switch to a list of mirrors
3) push the binaries in the repo. It was like that anyway.
4) add a script to update the local copy of the binaries, like we do with the private stuff. This can easily be combined with a check "is this the version I expect, if not, please download it".
5) make a debian package and have a fosdem repo somewhere with this kind of stuff (only if this isn't the only package, and this is pretty close to 2) )

AFAIK, 4) is what you're trying to do, but in ansible?

In any case, I hope to have a bit of time to play with it today.

**Comment by krokodilerian** [comment]
(wrote that on IRC,  but that's not the right place)
Actually, why not just download all architectures with a run_once task, and use those? Those are small, will most probably be needed anyway, and will not kill githun

**Comment by SuperQ** [comment]
1. It's already going to a CDN service, the real problem is NAT. This wouldn't be an issue if the video boxes had public IPs.
2. That's unrelated.
3. It's not the binaries that's the problem, it's the checksum validation fetch.
4. It's not the binaries, that part is already copied locally.
5. Something like packagecloud.io could be an option. They have free accounts for free software.
