### ISSUE TITLE
Don't run an open resolver

### ISSUE THREAD

**Issue by brian-brazil** [FOSDEM/infrastructure#25]
https://github.com/FOSDEM/infrastructure/commit/78479bd5645992528d9f1bb74706f59304bd4ac2 was added as a quick hack to unbreak serving of authoritive zones. We should switch this from controlling `allow-query` to controlling `allow-recursion`.

**Comment by SuperQ** [comment]
I already filed an upstream fix for the recursive issues.

**Comment by RichiH** [comment]
https://github.com/FOSDEM/infrastructure/issues/6

**Comment by SuperQ** [comment]
https://github.com/netzwirt/ansible-bind/pull/1 is the proper fix, I don't know ansible well enough how to overlay a fix for that other than adding some line replace.

**Comment by brian-brazil** [comment]
Fixed by https://github.com/FOSDEM/infrastructure/commit/c7f0f98d7d8e4c609e69b35369dfebe202cca3cc
