### ISSUE TITLE
Missing intermediate letsencrypt cert in nginx (was Infodesk Laptops Firefox complains about LetsEncrypt Certificates)

### ISSUE THREAD

**Issue by bastischubert** [FOSDEM/infrastructure#266]
While trying to use one of the Infodesk Laptops to access https://control.video.fosdem.org it refuses to connect SEC_ERROR_UNKNOWN_ISSUER - after updating Firefox esr to latest (apt update && apt upgrade) Problem still exists.

Why is this important: We need to connect to control.fosdem to check video and audio levels :/

**Comment by RichiH** [comment]
We are working on it and fix incoming in ~10m.

**Comment by RichiH** [comment]
Use FOSDEM-dualstack as a fallback for now

**Comment by krokodilerian** [comment]
@bastischubert can you retest?

**Comment by bastischubert** [comment]
infodesk laptop of us now working after importing the proper intermediate ca certs to the browser. seems like the control.video.fosdem.org server is miconfigured and does not toss out the intermediate certs

**Comment by bastischubert** [comment]
> Use FOSDEM-dualstack as a fallback for now

we have a certificate unknown signer issue - nothing with the underlying network at all ;)

**Comment by bastischubert** [comment]
see https://www.ssllabs.com/ssltest/analyze.html?d=control.video.fosdem.org&s=185.175.218.11

**Comment by krokodilerian** [comment]
Found the issue, we were missing the intermediate cert (someone reported it to us). This was also the case for stream.fosdem.org, making a note to get that fixed on all certs in ansible before closing this.

**Comment by krokodilerian** [comment]
Apologies. @bastischubert was the one who reported it, it's here two messages up, and my head seems to be somewhat missing.
