### ISSUE TITLE
Install Mermaid JS plugin via Ansible

### ISSUE THREAD

**Issue by RichiH** [FOSDEM/infrastructure#274]

**Comment by SuperQ** [comment]
This is for Grafana I assume?

**Comment by SuperQ** [comment]
This one? https://grafana.com/grafana/plugins/jdbranham-diagram-panel

**Comment by bastischubert** [comment]
Do we still need this, and if so what will we be doing with it? ;)

**Comment by RichiH** [comment]
Don't think so.

It was meant for network topolody
