### ISSUE TITLE
Replace git submodules by an Ansible requirements file

### ISSUE THREAD

**Issue by gerryd** [FOSDEM/infrastructure#308]
We are currently using git submodules for importing external roles:

- ansible/playbooks/roles/rsyslog
- ansible/playbooks/roles/paulfantom.restic
- ansible/playbooks/roles/caddy-ansible.caddy
- ansible/playbooks/roles/fosdem.bind
- ansible/playbooks/roles/nickjj.docker

Maybe we should switch to a requirements file?

**Comment by bastischubert** [comment]
switched to requirements file. will work on the prometheus roles in another issue the next days
