### ISSUE TITLE
Get T-shirt sale data into Prometheus

### ISSUE THREAD

**Issue by RichiH** [FOSDEM/infrastructure#87]

**Comment by RichiH** [comment]
@aghos

**Comment by SuperQ** [comment]
Great idea.

**Comment by RichiH** [comment]
We already talked this through, it will happen and we will make it public :)

Richard

Sent by mobile; excuse my brevity.

**Comment by SuperQ** [comment]
We'll need a new github repo for the `tshirt_exporter` :-D

**Comment by RichiH** [comment]
Plan is to have the shirt sale thing be a part of the infrastructure repo
or we create a new repo for it.

Richard

Sent by mobile; excuse my brevity.

**Comment by aghos** [comment]
i"ll create a repo for it, because some active development is needed.
But first i'll have to clean up the code.

**Comment by SuperQ** [comment]
@aghos What is the current code like that tracks the sales?

**Comment by aghos** [comment]
the current code is php with jquery and was written when I had the time at night

the first thing I should change is add a dynamic form than can be updated from the config file, clean up code, add some checks for get variables and remove the copy paste lines and make it more dynamic.

I believe I can do this in a general short periode of time.

**Comment by RichiH** [comment]
https://github.com/FOSDEM/frontdesk-t-shirt_tracker exists and we can all write to it.

@aghos You are free to do this in your own repo if you prefer, but given the "conference-in-a-box" thing, I would like to make it as easy as possible for others to copy from us.

**Comment by RichiH** [comment]
https://github.com/FOSDEM/frontdesk-t-shirt_tracker/issues/2
