### ISSUE TITLE
Monitoring - Ingest video data, especially sound

### ISSUE THREAD

**Issue by RichiH** [FOSDEM/infrastructure#94]
We should have "normal" paramaters of loudness, sync, left/right, etc and ideally expose those to the monitoring. We have many videos for 2016 with low volume, some with no sound, many too dark, etc pp.

At least part of those should be caught via instrumentation and alerts.

**Comment by SuperQ** [comment]
I was also thinking about a SPL Metric of some kind, which would allow
detection of disconnected mics.

**Comment by RichiH** [comment]
Aye, that's what I meant with "no sound", but the underlying technical answer may be more complex than I think.

Listening in on streams is still good, and needed, but we should detect stuff if people don't listen in for whatever reason.

**Comment by RichiH** [comment]
Colour distribution for "shadows against wall that's being recorded by mistake"

**Comment by Thulinma** [comment]
We should be able to provide audio levels for L/R in some shape or form, at least. Also - bitrate is a good indicator for movement/audio. And we can definitely provide the current bitrate of each stream.

**Comment by RichiH** [comment]
EBU R128 seems to be the specs we want for sound monitoring.

**Comment by Thulinma** [comment]
https://ffmpeg.org/ffmpeg-filters.html#astats <-- This might also be useful. Especially since we can relatively easily extract it.

**Comment by msuriar** [comment]
Working, we have data in prometheus and a grafana dashboard.

**Comment by RichiH** [comment]
https://grafana.n.fosdem.net/dashboard/db/video-audio
