### ISSUE TITLE
Administrative - Become a LIR -- Send out everything on 2016-10-01

### ISSUE THREAD

**Issue by RichiH** [FOSDEM/infrastructure#95]
We should send everything out on 01.10.2016 to minimize cost & maximize time.

**Comment by RichiH** [comment]
@gerryd  I can do it as well, but it's prolly easiest if you do it.

**Comment by gerryd** [comment]
Done, we are now a RIPE member as "be.fosdem". @RichiH, if you mail me your RIPE account, I will give you access.
